channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex 
  - blas 
  - ca-certificates 
  - certifi 
  - cffi 
  - cudatoolkit 
  - intel-openmp 
  - libedit 
  - libffi 
  - libgcc-ng 
  - libgfortran-ng 
  - libstdcxx-ng 
  - mkl 
  - mkl-service 
  - mkl_fft 
  - mkl_random 
  - ncurses 
  - ninja 
  - numpy 
  - numpy-base 
  - openssl 
  - pip 
  - pycparser 
  - readline 
  - setuptools 
  - six 
  - sqlite 
  - tk 
  - wheel 
  - xz 
  - zlib 
  - pip:
    - argparse 
    - backcall 
    - block-bootstrap-pytorch 
    - bootstrap-pytorch 
    - click 
    - cycler 
    - decorator 
    - h5py 
    - ipdb 
    - ipython 
    - ipython-genutils 
    - jedi 
    - kiwisolver 
    - matplotlib 
    - munch 
    - opencv-python 
    - pandas 
    - parso 
    - pexpect 
    - pickleshare 
    - pillow 
    - plotly 
    - pretrainedmodels 
    - prompt-toolkit 
    - protobuf 
    - ptyprocess 
    - pygments 
    - pyparsing 
    - python-dateutil 
    - pytz 
    - pyyaml 
    - retrying 
    - scipy 
    - seaborn 
    - skipthoughts 
    - tabulate 
    - tensorboardx 
    - torch
    - torchvision 
    - tqdm 
    - traitlets 
    - wcwidth 

